format = """
[](#DFF2D8)\
$username\
[](bg:#C6DEA6 fg:#DFF2D8)\
$directory\
[](fg:#C6DEA6 bg:#7EBDC3)\
$time\
[ ](fg:#7EBDC3)\
"""

[username]
show_always = true
style_user = "bold bg:#DFF2D8 fg:#515151"
style_root = "bg:#DFF2D8"
format = '[$user]($style)'

[directory]
style = "bold bg:#C6DEA6 fg:#515151"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[time]
disabled = false
time_format = "%a %b %e" # Day Month year format
style = "bold bg:#7EBDC3 fg:#515151"
format = '[  $time ]($style)'

[directory.substitutions]
"Documents" = "  "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "
"image's" = "  "
"Desktop" = " 󱈹 "
"~" = "  "
"coding" = "  "
"python" = "  "
"scripts" = "  "
"videos" = "  "
"school" = " 拾 "
"installers" = "  "
".config" = "  "

[c]
symbol = "  "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'


